[package]
name = "forest"
version = "1.0.0"
edition = "2021"
authors = ["yotka"]

[dependencies]
rand = "0.8.5"
rand_xorshift = "0.3.0"
str = "0.1.4"
strum = "0.25.0"
strum_macros = "0.25.2"

[[bin]]
name = "perf_test"
