[package]
name = "forest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
rand = "0.8.5"
str = "0.1.4"
strum = "0.25.0"
strum_macros = "0.25.2"
