[package]
name = "forest"
version = "1.0.0"
edition = "2021"
authors = ["yotka"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
str = "0.1.4"
strum = "0.25.0"
strum_macros = "0.25.2"
